import type { Metadata } from "next";

import "@/assets/styles/globals.css";
import { cn } from "@/lib/utils";
import { fontSerif, fontSans } from "@/assets/fonts";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import TanstackProvider from "@/providers/tanstack";

export const metadata: Metadata = {
  title: "Coiton",
  description: "Generated by create next app",
  icons: {
    icon: "/svgs/logo.svg",
  },
};

export default function RootLayout({ children }: TParentLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex flex-col flex-1 relative",
          fontSans.variable,
          fontSerif.variable
        )}>
        <div className="absolute -z-10 top-0 left-0 bg-gradient-to-b from-[#FFF4DE] via-[#FFF4DE]/50 to-background min-h-screen w-full" />

        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
